# -*- coding: utf-8 -*-
"""Implementacion de grafos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOOOuTOYj_XC8sPFVv7jGtROUd4J8HVB
"""

class Nodo:
    def __init__(self, nombre, piso, tipo):
        self.nombre = nombre
        self.piso = piso
        self.tipo = tipo

    def __repr__(self):
        return f"{self.nombre}(p{self.piso})"

    def __eq__(self, otro):
        return isinstance(otro, Nodo) and self.nombre == otro.nombre and self.piso == otro.piso

    def __hash__(self):
        return hash((self.nombre, self.piso))


class GrafoPonderado():

    def __init__(self, grafo=None):
        if grafo is None:
            grafo = {}
        self.grafo = grafo

    def __repr__(self):
        nodos = ''
        for nodo, aristas in self.grafo.items():
            nodos += f'{nodo}: {aristas}\n'
        return nodos

    def __iter__(self):
        self.iter_obj = iter(self.grafo)
        return self.iter_obj

    def nodos(self):
        return list(self.grafo.keys())

    def aristas(self, nodo=None):
        if nodo:
            if self.existeNodo(nodo):
                return [(nodo, a) for a in self.grafo[nodo]]
            else:
                return []
        else:
            return [(n, a) for n in self.grafo.keys() for a in self.grafo[n]]

    def nodosAislados(self):
        return [nodo for nodo in self.grafo if not self.grafo[nodo]]

    def orden(self):
        return len(self.grafo)

    def tamaño(self):
        arcos = []
        for nodo, aristas in self.grafo.items():
            for arista, p in aristas:
                arista_ordenada = tuple(sorted([nodo, arista], key=lambda x: x.nombre))
                if arista_ordenada not in arcos:
                    arcos.append(arista_ordenada)
        return len(arcos)

    def grado(self, nodo):
        if self.grafo == {}:
            return -1
        grado = len(self.grafo[nodo])
        if nodo in [n for n, _ in self.grafo[nodo]]:
            grado += 1
        return grado

    def Delta(self):
        if self.grafo == {}:
            return -1
        grados = [self.grado(nodo) for nodo in self.grafo]
        return max(grados)

    def agregarNodo(self, nodo):
        if nodo not in self.grafo:
            self.grafo[nodo] = []

    def eliminarNodo(self, nodo):
        if nodo in self.grafo:
            aristas = list(self.grafo[nodo])
            for arista, p in aristas:
                self.eliminarArista((nodo, arista))
            self.grafo.pop(nodo)

    def agregarArista(self, arista, peso):
        n1, n2 = tuple(arista)
        for n, a in [(n1, n2), (n2, n1)]:
            if n in self.grafo:
                if a not in [destino for destino, _ in self.grafo[n]]:
                    self.grafo[n].append((a, peso))
            else:
                self.grafo[n] = [(a, peso)]

    def eliminarArista(self, arista):
        n1, n2 = tuple(arista)
        for n, a in [(n1, n2), (n2, n1)]:
            if n in self.grafo:
                for nodo, peso in self.grafo[n]:
                    if nodo == a:
                        self.grafo[n].remove((nodo, peso))
                        break

    def encontrarRutas(self, inicio, fin, ruta=[]):
        if inicio not in self.grafo or fin not in self.grafo:
            return []
        ruta = ruta + [inicio]
        if inicio == fin:
            return [ruta]
        rutas = []
        for nodo, _ in self.grafo[inicio]:
            if nodo not in ruta:
                nuevas_rutas = self.encontrarRutas(nodo, fin, ruta)
                for subruta in nuevas_rutas:
                    rutas.append(subruta)
        return rutas

    def rutaMasCorta(self, inicio, fin):
        INF = float('inf')
        no_visitados = {nodo: INF for nodo in self.grafo.keys()}
        predecesor = {nodo: None for nodo in self.grafo.keys()}
        visitados = {}
        actual = inicio
        peso_actual = 0
        no_visitados[actual] = peso_actual

        while no_visitados:
            for nodo, peso in self.grafo[actual]:
                if nodo in no_visitados:
                    nuevo_peso = peso_actual + peso
                    if no_visitados[nodo] > nuevo_peso:
                        no_visitados[nodo] = nuevo_peso
                        predecesor[nodo] = actual

            visitados[actual] = peso_actual
            no_visitados.pop(actual)

            if not no_visitados:
                break

            actual, peso_actual = min(no_visitados.items(), key=lambda x: x[1])

        ruta = []
        nodo = fin
        while nodo is not None:
            ruta.append(nodo)
            nodo = predecesor[nodo]

        return (ruta[::-1], visitados[fin])

    def estaVacio(self):
        return self.grafo == {}

    def existeNodo(self, nodo):
        return nodo in self.grafo.keys()

    def existeArista(self, arista):
        n1, n2 = tuple(arista)
        return any(destino == n2 for destino, _ in self.grafo[n1]) or \
               any(destino == n1 for destino, _ in self.grafo[n2])


    def filtrar(self, tipo=None, piso=None):

        resultados = []

        for nodo in self.grafo.keys():

            cumple_tipo = (tipo is None or nodo.tipo == tipo)
            cumple_piso = (piso is None or nodo.piso == piso)

            if cumple_tipo and cumple_piso:
                resultados.append(nodo)

        return resultados


# ===================== NODOS DEMO =====================



entrada = Nodo("entrada",1,"entrada")
addidas = Nodo("addidas",1,"tienda")
juanvaldez = Nodo("Juan valdez",1,"restaurante")
nike = Nodo("nike",1,"tienda")
baño1 = Nodo("baño 1",1,"baño")
reebok = Nodo("Reebok",1,"tienda")
popsy = Nodo("popsy",1,"restaurante")
kfc = Nodo("kfc",1,"restaurante")
escalera1_2= Nodo("Escalera 1-2",0,"escalera")#le puse piso 0
d1 = Nodo("d1",2,"tienda")
koaj = Nodo("koaj",2,"tienda")
dolarcity = Nodo("dolarcity",2,"tienda")
baño2 = Nodo("baño 2 ",2,"baño")
hym = Nodo("HyM",2,"tienda")
ascensor = Nodo("Ascensor",0,"ascensor") #le puse piso 0
escalera2_3 = Nodo("Escalera 2-3",0,"escalera") #le puse piso 0
mattelsa = Nodo("mattelsa",3,"tienda")
mercagan = Nodo("mercagan",3,"restaurante")
baño3 = Nodo("baño 3",3,"baño")
cinecolombia = Nodo("Cine colombia",3,"entretenimiento")
casino = Nodo("Casino brodway",3,"entretenimiento")

# ===================== GRAFO DEMO =====================

grafo_dict = {
    entrada:   [(addidas, 2), (juanvaldez, 2)],
    addidas:    [(entrada, 2), (juanvaldez, 4), (nike, 5)],
    nike: [(baño1,1),(addidas,5)],
    baño1: [(nike,1),(reebok,1)],
    reebok: [(baño1,1),(escalera1_2,2),(kfc,4),(ascensor,1)],
    juanvaldez: [(entrada,2),(addidas,4),(popsy,6)],
    popsy: [(juanvaldez,6),(kfc,2)],
    kfc: [(popsy,2),(reebok,4),(ascensor,1)],
    ascensor: [(reebok,1),(kfc,1),(d1,1),(hym,1),(mercagan,2),(mattelsa,2)],
    d1: [(ascensor,1),(escalera1_2,3),(hym,4),(koaj,3)],
    koaj: [(d1,3),(dolarcity,4)],
    dolarcity: [(koaj,4),(baño2,1),(escalera2_3,2)],
    baño2: [(dolarcity,1),(hym,1)],
    hym: [(ascensor,1),(d1,4),(baño2,1)],
    mercagan: [(ascensor,2),(mattelsa,4),(baño3,2)],
    baño3: [(mercagan,2),(cinecolombia,1)],
    cinecolombia: [(baño3,1),(casino,4)],
    casino: [(cinecolombia,4),(mattelsa,3)],
    mattelsa: [(ascensor,2),(mercagan,4),(casino,3),(escalera2_3,3)]

}

G = GrafoPonderado(grafo_dict)

# ------------------ MENÚ PRINCIPAL ------------------
TIPOS_LUGAR = [
    "restaurante",
    "tienda",
    "baño",
    "entretenimiento",
    "escalera",
    "ascensor",
    "entrada",
    "salida"
]

while True:
    print("\n===== MENÚ =====")
    print("1. Ver nodos")
    print("2. Agregar nodo")
    print("3. Eliminar nodo")
    print("4. Filtrar")
    print("5. Salir")
    opcion = input("Opción: ")

    #---------------------- Ver nodos
    #imprime todos los nodos que hay, como ya hay un demo lo toma en cuenta :D
    if opcion == "1":
        print("\n--- Lista de nodos ---")
        for nodo in G.nodos():
            print(nodo, f"(tipo={nodo.tipo}, piso={nodo.piso})")

    #----------------------Agregar nodo
    # te pide nombre, piso, el tipo y la conexion con su distancia en minutos
    elif opcion == "2":
        try:
            print("\n== Crear nodo ==")
            nombre = input("Nombre del nodo: ")
            piso = int(input("Piso: "))

            print("\nTipos de lugar:")
            for i, t in enumerate(TIPOS_LUGAR, start=1):
                print(f"{i}. {t}")
                #imprime todos los lugares con un contador o numero
            tnum = int(input("Tipo (número): "))
            tipo = TIPOS_LUGAR[tnum - 1]

            nuevo = Nodo(nombre, piso, tipo)
            G.agregarNodo(nuevo)
            print("Nodo agregado:", nuevo)

            # solo conexiones del mismo piso, porque como se va a conectar un
            # lugar de diferentes pisos sin escaleras
            existentes = [n for n in G.nodos() if n != nuevo and n.piso == piso]

            if existentes:
                print("\nConectar con :")
                for i, n in enumerate(existentes, start=1):
                    print(f"{i}. {n}")

                sel = input("Número: ")
                if sel != "":
                    for idx in sel.split():
                        i = int(idx)-1
                        destino = existentes[i]
                        #esta es la distancia o tiempo estimado de A a B
                        peso = int(input(f"Peso entre {nuevo} y {destino}: "))
                        G.agregarArista((nuevo, destino), peso)
                        print("Conectado:", nuevo, "<->", destino)

        except:
            print("Error en la creación del nodo.")

    # 3 - Eliminar nodo
    elif opcion == "3":
        try:
            nodos = G.nodos()
            #por si no hay nodos
            if not nodos:
                print("No hay nodos para eliminar.")
                continue

            print("\n--- Selecciona el nodo a eliminar ---")
            for i, n in enumerate(nodos, start=1):
                print(f"{i}. {n} (tipo={n.tipo}, piso={n.piso})")

            sel = int(input("Número: ")) - 1

            if sel < 0 or sel >= len(nodos):
                print("Selección inválida.")
                continue

            elegido = nodos[sel]
            G.eliminarNodo(elegido)
            print("Nodo eliminado:", elegido)

        except:
            print("Error eliminando nodo.")

    # 4 - Filtrar
    elif opcion == "4":
        print("\nFiltrar por tipo (0 = ignorar):")
        print("0. Ignorar")
        for i, t in enumerate(TIPOS_LUGAR, start=1):
            print(f"{i}. {t}")
        ft = input("Tipo: ")
        tipo = None
        if ft not in ("", "0"):
            tipo = TIPOS_LUGAR[int(ft)-1]

        pisos = sorted({n.piso for n in G.nodos()})
        print("\nFiltrar por piso (0 = ignorar):")
        for p in pisos:
            print("-", p)
        fp = input("Piso: ")
        piso = None
        if fp not in ("", "0"):
            piso = int(fp)

        res = G.filtrar(tipo=tipo, piso=piso)
        print("\n--- Resultados ---")
        for r in res:
            print(r, f"(tipo={r.tipo}, piso={r.piso})")
        if not res:
            print("Nada encontrado.")

    # 5 - Salir
    elif opcion == "5":
        print("Saliendo...")
        break

    else:
        print("Opción inválida.")